### ISSUE TITLE
Support named buses

### ISSUE THREAD

**Issue by jabdoa2** [kplindegaard/smbus2#17]
It would be nice to support named devices for USB-I2C adapters such as tiny-i2c-usb because their bus number will not be consistent between restarts. However, we can create symlinks using udev. Currently, I just symlink to /dev/i2c-my-bus1 and use "my-bus1" as bus id in smbus2. Works as a hack but it is probably not intended this way.

**Comment by kplindegaard** [comment]
Above mentioned PR lets you provide the full path, i.e. you can choose between bus number (int) and a string containing a full path.

**Comment by jabdoa2** [comment]
Awesome thanks!
