### ISSUE TITLE
error in smbus2 setup command: 'extras_require'

### ISSUE THREAD

**Issue by ash73** [kplindegaard/smbus2#21]
Hi, trying to install smbus2 on a rPi2, because something else I am trying to install(!) may have a dependency on it, but smbus2 install fails:

sudo python setup.py install

error in smbus2 setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.

I had a look in setup.py and it says:
    extras_require={
        'docs': [
            'sphinx >= 1.5.3'
        ],
        'qa': [
            'flake8'
        ],
        'test': test_deps
    }

But I have no idea how to fix it.

Please help.

**Comment by kplindegaard** [comment]
Works like a charm on my Linux box with Python 2.7.13 and setuptools 36.4.0.

You can try to delete the `extras_require` and install. It's not strictly necessary for installing the core of the lib.

**Comment by tedder** [comment]
Dead ticket, but maybe it's a py3/pip3 problem.

**Comment by ash73** [comment]
My Raspbian install must have been corrupted somehow, I created a fresh install and everything works ok.
