### ISSUE TITLE
Reason for SmBusWrapper class

### ISSUE THREAD

**Issue by kungpfui** [kplindegaard/smbus2#24]
Hi,

I am just wondering why you have added the SMBusWrapper class instead of extending the SmBus class itself by enter/exit handlers?
For me it looks rather unnecessary but maybe I just don't get it.

P.S. Great python library! It just works ... and the only working i2c_rdwr implementation I've found.

**Comment by kplindegaard** [comment]
@kungpfui, thanks. 

You are correct. There isn't really a reason for the SMBusWrapper class. I've thought about getting rid of it several times.

**Comment by kplindegaard** [comment]
Will be part of 0.3.0. Kept the old SMBusWrapper class for backwards compatibility until the next update after 0.3.x comes.
