### ISSUE TITLE
ImportError: cannot import name 'ic_msg'

### ISSUE THREAD

**Issue by afan09** [kplindegaard/smbus2#34]
i just did 
`sudo python3 setup.py install`
then when i try :
`from smbus2 import SMBus, ic_msg`

it give me an error like that..
`ImportError                               Traceback (most recent call last)
<ipython-input-21-d29c59164a39> in <module>
----> 1 from smbus2 import SMBus, ic_msg
      2 import pydoc

ImportError: cannot import name 'ic_msg'`

**Comment by kplindegaard** [comment]
Given your import statement, that's the correct behavior. There is no `ic_msg` in the lib. 
Now, there is a class called `i2c_msg`, ref. example 5 in README.md.
