### ISSUE TITLE
Read smbus 32 byte Block data

### ISSUE THREAD

**Issue by scottscott70** [kplindegaard/smbus2#48]
I use read_i2c_block_data function to read bq40z55 data flash
but once block_data have 36 Byte, i2c_block_data function limit to 32 Byte
how can I do read all 36 Byte Block data
![image](https://user-images.githubusercontent.com/67775161/86435147-dbfc1780-bd31-11ea-87e5-8db649f1836b.png)

**Comment by kplindegaard** [comment]
Hi @scottscott70 
Take a look at [Example 5](https://github.com/kplindegaard/smbus2#example-5-single-i2c_rdwr) in the readme.

**Comment by scottscott70** [comment]
Thanks for your reply.
After the test, the i2c waveform was correct.
But how to get data buffer?
Now , I get data buffer is nano.
This smbus2 module was perfect. Thank You.

![image](https://user-images.githubusercontent.com/67775161/86507607-2a7de480-be0c-11ea-89c2-6bd94566881a.png)
![image](https://user-images.githubusercontent.com/67775161/86507629-6022cd80-be0c-11ea-8d7e-ac2d543f8994.png)

**Comment by scottscott70** [comment]
Buy the way, "pip install smbus2" is not working Now.

**Comment by scottscott70** [comment]
Sorry, I got data succesfully

![image](https://user-images.githubusercontent.com/67775161/86508261-2b654500-be11-11ea-9e21-c64a601821b5.png)
![image](https://user-images.githubusercontent.com/67775161/86508285-66677880-be11-11ea-91ef-37cbc62a12ba.png)
