### ISSUE TITLE
Can I call it in C + +?

### ISSUE THREAD

**Issue by Culturenotes** [kplindegaard/smbus2#57]
I think it's OK to use C + + language? , how can I use it? Do you have a reference code?

**Comment by kplindegaard** [comment]
Not sure if I quite caught what you meant... Call smbus2 for Python from C++? You definitely don't want to do that.

It will be a lot easier to perform i2c operations in C and C++, and there are plenty of examples out there if you search a little. Also check the [Linux kernel pages i2c docs](https://www.kernel.org/doc/html/latest/i2c/index.html).
