### ISSUE TITLE
SMBus Quick Command

### ISSUE THREAD

**Issue by Jonathan-Rosewood** [kplindegaard/smbus2#7]
> SMBus Quick Command
> ===================
> 
> This sends a single bit to the device, at the place of the Rd/Wr bit.
> 
> A Addr Rd/Wr [A] P
> 
> Functionality flag: I2C_FUNC_SMBUS_QUICK
from https://www.kernel.org/doc/Documentation/i2c/smbus-protocol

**Comment by Jonathan-Rosewood** [comment]
It is very useful for scanning a bus for connected devices

**Comment by kplindegaard** [comment]
Added `write_quick(addr)` method to the SMBus class. Closing this request.
